[package]
name = "jsm-resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
jsm-core = { path = "../jsm-core" }
pubgrub = "0.4"
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
