[package]
name = "jsm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "jsm"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
fs4.workspace = true
ctrlc.workspace = true
jsm-fetch = { path = "../jsm-fetch" }
jsm-core = { path = "../jsm-core" }
jsm-linker = { path = "../jsm-linker" }
jsm-lockfile = { path = "../jsm-lockfile" }
jsm-registry = { path = "../jsm-registry" }
jsm-resolver = { path = "../jsm-resolver" }
jsm-store = { path = "../jsm-store" }
miette.workspace = true
indicatif.workspace = true
semver.workspace = true
serde_json.workspace = true
toml.workspace = true
base64.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd = "2.0"
jsm-testkit = { path = "../jsm-testkit" }
tempfile.workspace = true

[lints]
workspace = true
