[profile.default]
fail-fast = false
status-level = "fail"
final-status-level = "slow"

[profile.ci]
fail-fast = false
status-level = "fail"
final-status-level = "slow"
failure-output = "immediate-final"
